### PR TITLE
ISPN-9855 Upgrade to SB 2.1.2.RELEASE

### PR DESCRIPTION
**Pull request by DanielFran**
https://issues.jboss.org/browse/ISPN-9855

Closes: https://github.com/infinispan/infinispan-spring-boot/issues/88

### CODE REVIEW

**Comment by DanielFran** [comment]
@karesti is it ok for you?

**Comment by karesti** [comment]
@DanielFran there is something weird with the commits. I prefer a single commit with the component updates if you don't mind. The Pr is not mergeable because there are some conflicts!

**Comment by DanielFran** [comment]
@karesti this is wird because the conflits are the changes I am doing...
Anyway, I will create a PR per update on few minutes.

**Comment by DanielFran** [comment]
Created new PR https://github.com/infinispan/infinispan-spring-boot/pull/90

**Pull request closed without merging**
