### PR TITLE
ISPN-11546 Upgrade to 2.2.6.RELEASE

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-11546

### CODE REVIEW

**Comment by pruivo** [comment]
I guess we need to wait for GA before merging changes right @karesti ?

**Comment by karesti** [comment]
@pruivo I don't know

**Comment by karesti** [comment]
do we ?

**Comment by pruivo** [comment]
GA is planned for April 1st. I'll merge it tomorrow.

**Comment by pruivo** [comment]
integrated! thanks @karesti !

**Pull request merged**
