### PR TITLE
Add possibility to cache meter binder overriding

### PR DESCRIPTION
**Pull request by rutkowskij**
I've encountered problem with default cache meter binder and replicated or distributed embedded cache configuration. Default binder uses stats methods wchich agregate stats from all nodes. This behavior results timouts on /actuator/prometheus endpoints (it took several seconds)

I've prepared PR wchich enables overriding default binding configuration (and showed it in associated test)
I've disabled ```@ComponentScan``` at all. It was used only for binder configuration wchich is easy to create beans by ```@Configuration``` clases. Disabled component scan (wchich was enabled globally) should be also valuable for projects wchich not use that mechanizm at all (especially startup time should decreased)

### CODE REVIEW

**Comment by rutkowskij** [comment]
if meter binder is configured by autoconfiguration class it can be also easy disabled by 
```java
@SpringBootApplication(exclude = InfinispanCacheMeterBinderProviderAutoConfiguration.class)
```

**Comment by karesti** [comment]
@rutkowskij thanks for the contribution!

**Comment by karesti** [comment]
@rutkowskij This patch can't be integrated as it is in the next release, because it needs more thinking and testing.
The problem you raise is that there are timeouts due to the call stats. Is there any particular method you are experiencing this?
Would a bean that interacts with the local cache instead os each node instead of the distributed/replicated values seem like a good option?

**Comment by karesti** [comment]
@rutkowskij For what is the remove of the component scan, we need to test that removing those annotations won't break actual applications using this starter

**Comment by karesti** [comment]
I'm closing this issue for now, and opening a JIRA for further work to be done on this matter

**Comment by karesti** [comment]
https://issues.redhat.com/browse/ISPN-11194

**Pull request closed without merging**
