### PR TITLE
Upgrade 2.1.3.RELEASE and fix samples pom

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-9984

- The spring-boot maven plugin must be placed in the `pom.xml` where we want to run spring-boot:run

- Upgraded the reinforce plugin that was failing the build in java 11

- Upgraded SB 2.1.3.RELEASE

- Upgraded Infinispan 9.4.8.Final

- Using the correct wildfly maven plugin

Closes https://github.com/infinispan/infinispan-spring-boot/issues/101

### CODE REVIEW

**Comment by karesti** [comment]
@geoand hi, if you have some time to grab a quick look and merge would be awesome!  💃

**Comment by geoand** [comment]
I'll try, but we have a f2f this week so not sure how much time I'll have
to spare 😎

**Comment by karesti** [comment]
@geoand I will grab someone from infinispan then, don't worry and enjoy!!

**Comment by tristantarrant** [comment]
Can you please squash the commits and add  a Jira ?

**Comment by karesti** [comment]
@tristantarrant usually do it without being told, but I totally forgot it this time with all this previous debugging! Done https://issues.jboss.org/browse/ISPN-9984

**Comment by geoand** [comment]
Thanks @karesti

**Comment by DanielFran** [comment]
This will be updated to 9.4.8.Final?

**Comment by karesti** [comment]
@DanielFran yes

**Pull request merged**
