### PR TITLE
ISPN-9668 Integration with actuator

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-9668

The pr contains two additional commits, a typo fix and the checkstyle integration to the build. 
Ignore those commits, please

### CODE REVIEW

**Comment by galderz** [comment]
Looks good. My only doubt is whether the actuator integration to show the statistics should live in this repository or in [infinispan/infinispan/tree/master/spring/spring4](https://github.com/infinispan/infinispan/tree/master/spring/spring4). Is this actuator stuff specific to Spring Boot? If it's relevant to both Spring and Spring Boot apps, it should probably live in the main repo?

**Comment by karesti** [comment]
@galderz it's relevant mainly for spring-boot, but it can be used without, so probably should live in the same repo. However, our infinispan release cycles differ from spring-boot ones, so I'm considering implementing it here and moving it to spring4 (spring5 when the times comes) and refactor from here once the spring jar contains these metric implementations. WDYT ?

**Comment by galderz** [comment]
Sounds good! :)

**Comment by karesti** [comment]
@galderz I added two examples using actuator and exposing the metrics

**Comment by geoand** [comment]
@karesti @galderz The Actuator is a Spring Boot specific concept. 
So it's not like Spring MVC which is part of Spring Framework and made super easy to use in Spring Boot. Actuator is a wholly Spring Boot specific thing :)

**Comment by karesti** [comment]
@geoand I read the opposite here https://stackoverflow.com/questions/29953157/spring-boot-actuator-without-spring-boot

**Comment by geoand** [comment]
@karesti Very interesting! I have never seen anyone do that before :P, thanks for pointing this out! 
So it seems like it's technically possible, but you have to jump through some hoops to get there and FWIW I have never seen anyone use the actuator without SB :P

**Comment by snicoll** [comment]
For the record, the Actuator is a Spring Boot specific concept. I wouldn't recommend to bother about a use case where someone tries to make that work in a non Spring Boot application (as we don't officially support that).

**Comment by geoand** [comment]
@snicoll Thank you for your expert perspective :)

**Comment by karesti** [comment]
@galderz reviewable and mergeable

**Comment by geoand** [comment]
@karesti Looks great :+1: 

I just have a minor suggestions:

It would be nice to explain in the README why you are explicitly declaring the cache names in infinispan configuration

**Comment by karesti** [comment]
Yes I realized that I didn’t document the readme haha

I’m going to do that in a separate commit and I think this is ready for
merge and released

**Comment by geoand** [comment]
FWIW, it looks great to me :)

**Comment by karesti** [comment]
Documentation added

**Comment by galderz** [comment]
Thx @karesti :)

**Pull request merged**
