### PR TITLE
ISPN-9437 translation hotrod properties into spring yaml

### PR DESCRIPTION
**Pull request by karesti**
Can't be integrated yet. I'm modify at the same time infinispan for the 9.4 release. 
Will be mergeable with Infinispan 9.4.0.Final

https://issues.jboss.org/browse/ISPN-9437

Related to  https://github.com/infinispan/infinispan-spring-boot/issues/48

### CODE REVIEW

**Comment by galderz** [comment]
@karesti Is this ready to be reviewed? The do not integrate tag is still on

**Comment by karesti** [comment]
@galderz can be reviewed

**Comment by karesti** [comment]
@galderz not in this PR

**Comment by karesti** [comment]
@galderz I would like to merge and release 2.0.0 😄

**Pull request merged**
