### PR TITLE
ISPN-9820 Remove release step from jenkins file

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-9820

### CODE REVIEW

**Comment by ryanemerson** [comment]
@karesti I don't know enough about how the spring release works from Jenkins so this might not make sense, but do we not still need a release stage? Albeit without the user input.

**Comment by karesti** [comment]
@ryanemerson yes, and this is done with the jenkinsfile-release, not the regular jenkins file to build the pr

**Comment by karesti** [comment]
@ryanemerson here https://github.com/infinispan/infinispan-spring-boot/blob/master/Jenkinsfile-release

**Comment by karesti** [comment]
@ryanemerson don't be shy, and click merge button, be my guest! ❤️

**Pull request merged**
