### PR TITLE
Upgrade Infinispan and Spring-Boot version

### PR DESCRIPTION
**Pull request by karesti**
- 9.4.14.Final Infinispan
- 2.1.5.RELEASE Spring-Boot

### CODE REVIEW

**Comment by geoand** [comment]
CI didn't seem to like it :(

**Comment by karesti** [comment]
@geoand the issue is related to testcontainers that does not start in our CI ... I upgraded the test to use Junit5 and Infinispan Server extension. We are working on an out of the box testing utils of infinispan server, but the project is not released yet, so I'm adding what it need to be added for this simple test

**Comment by karesti** [comment]
@geoand feel free to merge! 💃

**Comment by geoand** [comment]
done :tada:

**Pull request merged**
