### PR TITLE
ISPN-12306 9.4 SB versions

### PR DESCRIPTION
**Pull request by oraNod**
https://issues.redhat.com/browse/ISPN-12306

### CODE REVIEW

**Comment by karesti** [comment]
@oraNod best to know is pedro about product release

**Comment by pruivo** [comment]
@oraNod those versions are for the upcoming release (DG 7.3.7). is it what you want?

**Comment by oraNod** [comment]
> @oraNod those versions are for the upcoming release (DG 7.3.7). is it what you want?

@pruivo yep, I want to update the versions in docs for the 7.3.7 release.

**Comment by pruivo** [comment]
integrated! thank @oraNod

**Pull request merged**
